apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-staging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: 6.14.1
      helm:
        valueFiles:
          - $values/argocd/apps/podinfo/values-staging.yaml

    - repoURL: https://github.com/jbazydlo/appdeploy-gitops.git
      targetRevision: 2-set-up-multi-environment-structure
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
